---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2

inputs:
- name: pcf-pipelines 
- name: pivnet-opsmgr
- name: terraform-state

outputs:
- name: create-infrastructure-output

params:
  GCP_PROJECT_ID:
  GCP_REGION:
  GCP_SERVICE_ACCOUNT_KEY:
  GCP_ZONE_1:
  GCP_ZONE_2:
  GCP_ZONE_3:
  GCP_RESOURCE_PREFIX:
  PCF_ERT_DOMAIN:
  PCF_ERT_SSL_CERT:
  PCF_ERT_SSL_KEY:
  DB_APP_USAGE_SERVICE_USERNAME:
  DB_APP_USAGE_SERVICE_PASSWORD:
  DB_AUTOSCALE_USERNAME:
  DB_AUTOSCALE_PASSWORD:
  DB_DIEGO_USERNAME:
  DB_DIEGO_PASSWORD:
  DB_NOTIFICATIONS_USERNAME:
  DB_NOTIFICATIONS_PASSWORD:
  DB_ROUTING_USERNAME:
  DB_ROUTING_PASSWORD:
  DB_UAA_USERNAME:
  DB_UAA_PASSWORD:
  DB_CCDB_USERNAME:
  DB_CCDB_PASSWORD:
  DB_ACCOUNTDB_USERNAME:
  DB_ACCOUNTDB_PASSWORD:
  DB_NETWORKPOLICYSERVERDB_USERNAME:
  DB_NETWORKPOLICYSERVERDB_PASSWORD:
  DB_NFSVOLUMEDB_USERNAME:
  DB_NFSVOLUMEDB_PASSWORD:

run:
  path: pcf-pipelines/tasks/install-pcf-gcp/create-infrastructure/task.sh
